"""Sovereign acquisition categories and default ammo split weights."""

ACQUISITION_CATEGORIES = {
    "compute": "VPS clusters, GPUs, HA replicas, edge compute",
    "network": "Starlink, Peplink, sovereign mesh, failover links",
    "storage": "NAS, cold archive, encrypted backup targets",
    "comms": "Sovereign mail, DNS, domain control, MX independence",
    "voice": "Self-hosted voice stack, SIP trunks, LiveKit",
    "security": "HSM, YubiKey fleet, vault hardware, IDS",
    "physical_ops": "Ground force kits, rugged laptops, mobile command",
    "energy": "Solar, battery, UPS for edge nodes",
}

# Percent of ammo pool split (must sum to 100)
DEFAULT_AMMO_WEIGHTS: dict[str, int] = {
    "compute": 25,
    "network": 20,
    "storage": 10,
    "comms": 10,
    "voice": 10,
    "security": 15,
    "physical_ops": 10,
}

DEFAULT_ACQUISITIONS: list[dict] = [
    {
        "category": "network",
        "name": "Starlink Business Kit",
        "description": "Sovereign internet failover when ISP or cell fails. Empire nodes stay online.",
        "equipment_spec": (
            "Starlink Business or Flat High Performance. Self-hosted routing via Peplink. "
            "No consumer dependency for command uplink."
        ),
        "target_cost_cents": 250000,
        "priority": 8,
        "empire_tier": 2,
        "vendor_candidates": "Starlink Business · Peplink BR1 Pro 5G combo",
    },
    {
        "category": "network",
        "name": "Peplink Multi-WAN Router",
        "description": "Bond Starlink + LTE + wired WAN. Automatic failover for VPS tunnel and voice.",
        "equipment_spec": "Peplink Balance or MAX series. Supports SpeedFusion VPN to Servury VPS.",
        "target_cost_cents": 89900,
        "priority": 7,
        "empire_tier": 2,
        "vendor_candidates": "Peplink BR1 Pro 5G · Balance 20X",
    },
    {
        "category": "compute",
        "name": "Servury VPS Expansion Node",
        "description": "Additional sovereign compute for n8n HA, Postgres replica, agent workers.",
        "equipment_spec": f"Servury VPS — ${3.99}/mo baseline per city node; scale to dedicated metal at tier 3.",
        "target_cost_cents": 39900,
        "priority": 9,
        "empire_tier": 1,
        "vendor_candidates": "Servury API provision",
    },
    {
        "category": "storage",
        "name": "Encrypted NAS — Empire Archive",
        "description": "Local vault mirror, ledger backups, Obsidian sync target.",
        "equipment_spec": "Synology or TrueNAS with LUKS/ZFS encryption. Min 4TB RAID1.",
        "target_cost_cents": 65000,
        "priority": 6,
        "empire_tier": 2,
        "vendor_candidates": "Synology DS923+ · TrueNAS Mini",
    },
    {
        "category": "comms",
        "name": "Sovereign Mail Stack",
        "description": "Replace Gmail dependency. Self-hosted IMAP/SMTP under empire domain.",
        "equipment_spec": "Mailcow or Stalwart on VPS. DKIM/SPF/DMARC. Agent inbox API.",
        "target_cost_cents": 0,
        "priority": 9,
        "empire_tier": 1,
        "vendor_candidates": "Mailcow Docker · Stalwart · Migadu bridge phase",
    },
    {
        "category": "voice",
        "name": "Self-Hosted LiveKit Voice Node",
        "description": "SARA/voice hotline without Vapi vendor lock-in path.",
        "equipment_spec": "LiveKit server on VPS + SIP bridge. Phase 2 migration from Vapi.",
        "target_cost_cents": 5000,
        "priority": 5,
        "empire_tier": 2,
        "vendor_candidates": "LiveKit OSS · daily.co bridge interim",
    },
    {
        "category": "security",
        "name": "YubiKey Commander Fleet",
        "description": "Hardware 2FA for portal, VPS, treasury approvals.",
        "equipment_spec": "YubiKey 5 NFC × 3 (primary, backup, travel). FIDO2 + PIV.",
        "target_cost_cents": 18000,
        "priority": 8,
        "empire_tier": 1,
        "vendor_candidates": "Yubico direct",
    },
    {
        "category": "physical_ops",
        "name": "Mobile Command Kit",
        "description": "Rugged laptop + LTE hotspot for ground force oversight in field.",
        "equipment_spec": "ThinkPad T series or Panasonic Toughbook. Secondary Starlink Mini optional.",
        "target_cost_cents": 120000,
        "priority": 6,
        "empire_tier": 2,
        "vendor_candidates": "Lenovo refurb · Dell Rugged",
    },
    {
        "category": "physical_ops",
        "name": "KC Ground Force Starter Kit",
        "description": "QR stickers, host one-pagers, branded cards for guerrilla guest outreach.",
        "equipment_spec": "500 stickers, 200 cards, 50 host packets. Local print shop.",
        "target_cost_cents": 35000,
        "priority": 9,
        "empire_tier": 1,
        "vendor_candidates": "Local KC print · Vistaprint rush",
    },
    {
        "category": "energy",
        "name": "Edge Node UPS + Solar",
        "description": "Keep command node alive through outages. Physical sovereignty.",
        "equipment_spec": "EcoFlow Delta or Bluetti + 400W panel. 24h runtime target.",
        "target_cost_cents": 150000,
        "priority": 4,
        "empire_tier": 3,
        "vendor_candidates": "EcoFlow Delta Pro · Bluetti AC200P",
    },
    {
        "category": "compute",
        "name": "n8n HA Postgres Replica",
        "description": "Workflow orchestration survives single VPS death.",
        "equipment_spec": "Second Servury VPS + Postgres streaming replica. n8n queue mode.",
        "target_cost_cents": 39900,
        "priority": 7,
        "empire_tier": 2,
        "vendor_candidates": "Servury second region",
    },
]
